apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-heo
spec:
  displayName: Heo
  author:
    name: Hyouka
    website: 'https://www.hyouka.link'
  description: Halo 2.0 Theme base on Thymeleaf, Referring to Butterfly and Heo
  logo: 'https://www.hyouka.link/upload/favicon.svg'
  website: 'https://www.hyouka.link'
  repo: 'https://github.com/hyouka-oasis/halo-theme-heo'
  settingName: "theme-hao-setting"
  configMapName: "theme-hao-configMap"
  version: 1.0.2
  require: 2.0.0
